### ISSUE TITLE
Error updating, connection aborted, remote end closed connection without response

### ISSUE THREAD

**Issue by Fywqdk** [jlvcm/ha-actualbudget#12]
Hi, I have been struggling a bit with this error which renders the integration useless most of the time due to error when updating values.

log file in HA:

`Denne fejl stammer fra en brugerdefineret integration.

Logger: custom_components.actualbudget.sensor
Kilde: custom_components/actualbudget/sensor.py:300
integration: actualbudget (dokumentation, problemer)
Første forekomst: 15.22.46 (34 forekomster)
Senest logget: 15.22.46

Unknown error updating data from ActualBudget API to budget 🏘️💳 Fælles Abonnementer. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Unknown error updating data from ActualBudget API to budget DP35 Husforsikring. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Unknown error updating data from ActualBudget API to budget 👨‍👩‍👧‍👦🤞 Gruppeliv etc. i bank. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Unknown error updating data from ActualBudget API to budget ⚽🏹 Sport. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Unknown error updating data from ActualBudget API to budget 🚗 🌉 Diesel, offentlig transport, parkering, bro/færge. ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/actualbudget/sensor.py", line 300, in async_update
    budget = await api.get_budget(self._name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 117, in get_budget
    return await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/actualbudget/actualbudget.py", line 126, in get_budget_sync
    with Actual(
         ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/actual/__init__.py", line 83, in __init__
    super().__init__(base_url, token, password, bootstrap, cert)
  File "/usr/local/lib/python3.12/site-packages/actual/api/__init__.py", line 72, in __init__
    self.validate()
  File "/usr/local/lib/python3.12/site-packages/actual/api/__init__.py", line 134, in validate
    response = self._requests_session.get(f"{self.api_url}/{Endpoints.ACCOUNT_VALIDATE}", verify=self.cert)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

I have been having a hard time identifying what was wrong. My python skills are not really on a level to deal with this level of errors, but then today I went and checked the log on my Actual server container, which seems to offer a hint (I think):

`actualbudget
date	stream	content
2024/11/21 15:45:56	stdout	2024-11-21T14:45:56.105Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:45:55	stdout	2024-11-21T14:45:55.168Z [32minfo[39m: GET 304 /account/validate
2024/11/21 15:45:52	stdout	2024-11-21T14:45:52.351Z [32minfo[39m: GET 304 /sync/list-user-files
2024/11/21 15:45:51	stdout	2024-11-21T14:45:51.952Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:45:48	stdout	2024-11-21T14:45:48.826Z [32minfo[39m: GET 304 /account/validate
2024/11/21 15:22:55	stdout	2024-11-21T14:22:55.683Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:54	stdout	2024-11-21T14:22:54.764Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:53	stdout	2024-11-21T14:22:53.168Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:52	stdout	2024-11-21T14:22:52.661Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:52	stdout	2024-11-21T14:22:52.442Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:52	stdout	2024-11-21T14:22:52.308Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:51	stdout	2024-11-21T14:22:51.610Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:51	stdout	2024-11-21T14:22:51.515Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:51	stdout	2024-11-21T14:22:51.252Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:50	stdout	2024-11-21T14:22:50.865Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:50	stdout	2024-11-21T14:22:50.504Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:50	stdout	2024-11-21T14:22:50.413Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:50	stdout	2024-11-21T14:22:50.331Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:50	stdout	2024-11-21T14:22:50.195Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:50	stdout	2024-11-21T14:22:50.090Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:49	stdout	2024-11-21T14:22:49.902Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:49	stdout	2024-11-21T14:22:49.814Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:49	stdout	2024-11-21T14:22:49.706Z [32minfo[39m: POST 200 /sync/sync
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.723Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.689Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.657Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.656Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.606Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.605Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.578Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.556Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.477Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.433Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.432Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.412Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.313Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.312Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.236Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.204Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.193Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:48	stdout	2024-11-21T14:22:48.139Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.469Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.453Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.342Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.329Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.328Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.326Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.323Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.322Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.321Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.320Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.319Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.319Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.318Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.317Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.315Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.315Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.314Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.312Z [32minfo[39m: GET 200 /sync/download-user-file
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.110Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.108Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.103Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.100Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.097Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.095Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.093Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.092Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.090Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.086Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.085Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.083Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.081Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.079Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.076Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.074Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.072Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.071Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.069Z [32minfo[39m: GET 200 /sync/list-user-files
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.067Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.065Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.063Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.062Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.060Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.058Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.055Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.053Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.052Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.050Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.049Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.047Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.045Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.044Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.042Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.040Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.038Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:46	stdout	2024-11-21T14:22:46.034Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:45	stdout	Logging in via password
2024/11/21 15:22:45	stdout	2024-11-21T14:22:45.750Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:45	stdout	Logging in via password
2024/11/21 15:22:45	stdout	2024-11-21T14:22:45.467Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:45	stdout	Logging in via password
2024/11/21 15:22:45	stdout	2024-11-21T14:22:45.178Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:44	stdout	Logging in via password
2024/11/21 15:22:44	stdout	2024-11-21T14:22:44.896Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:44	stdout	Logging in via password
2024/11/21 15:22:44	stdout	2024-11-21T14:22:44.619Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:44	stdout	Logging in via password
2024/11/21 15:22:44	stdout	2024-11-21T14:22:44.339Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:44	stdout	Logging in via password
2024/11/21 15:22:44	stdout	2024-11-21T14:22:44.050Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:43	stdout	Logging in via password
2024/11/21 15:22:43	stdout	2024-11-21T14:22:43.773Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:43	stdout	Logging in via password
2024/11/21 15:22:43	stdout	2024-11-21T14:22:43.496Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:43	stdout	Logging in via password
2024/11/21 15:22:43	stdout	2024-11-21T14:22:43.219Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:43	stdout	Logging in via password
2024/11/21 15:22:42	stdout	2024-11-21T14:22:42.938Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:42	stdout	Logging in via password
2024/11/21 15:22:42	stdout	2024-11-21T14:22:42.658Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:42	stdout	Logging in via password
2024/11/21 15:22:42	stdout	2024-11-21T14:22:42.383Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:42	stdout	Logging in via password
2024/11/21 15:22:42	stdout	2024-11-21T14:22:42.094Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:41	stdout	Logging in via password
2024/11/21 15:22:41	stdout	2024-11-21T14:22:41.767Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:41	stdout	Logging in via password
2024/11/21 15:22:41	stdout	2024-11-21T14:22:41.467Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:41	stdout	Logging in via password
2024/11/21 15:22:41	stdout	2024-11-21T14:22:41.193Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:41	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:40.913Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:40.633Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:40.352Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:40.076Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:39.797Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:39.518Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:40	stdout	2024-11-21T14:22:39.240Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:40	stdout	Logging in via password
2024/11/21 15:22:38	stdout	2024-11-21T14:22:38.956Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:38	stdout	Logging in via password
2024/11/21 15:22:38	stdout	2024-11-21T14:22:38.680Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:38	stdout	Logging in via password
2024/11/21 15:22:38	stdout	2024-11-21T14:22:38.404Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:38	stdout	Logging in via password
2024/11/21 15:22:38	stdout	2024-11-21T14:22:38.116Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:37	stdout	Logging in via password
2024/11/21 15:22:37	stdout	2024-11-21T14:22:37.839Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:37	stdout	Logging in via password
2024/11/21 15:22:37	stdout	2024-11-21T14:22:37.552Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:37	stdout	Logging in via password
2024/11/21 15:22:37	stdout	2024-11-21T14:22:37.260Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:36	stdout	Logging in via password
2024/11/21 15:22:36	stdout	2024-11-21T14:22:36.887Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:36	stdout	Logging in via password
2024/11/21 15:22:36	stdout	2024-11-21T14:22:36.549Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:36	stdout	Logging in via password
2024/11/21 15:22:36	stdout	2024-11-21T14:22:36.262Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:35	stdout	Logging in via password
2024/11/21 15:22:35	stdout	2024-11-21T14:22:35.985Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:35	stdout	Logging in via password
2024/11/21 15:22:35	stdout	2024-11-21T14:22:35.708Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:35	stdout	Logging in via password
2024/11/21 15:22:35	stdout	2024-11-21T14:22:35.430Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:35	stdout	Logging in via password
2024/11/21 15:22:35	stdout	2024-11-21T14:22:35.154Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:34	stdout	Logging in via password
2024/11/21 15:22:34	stdout	2024-11-21T14:22:34.878Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:34	stdout	Logging in via password
2024/11/21 15:22:34	stdout	2024-11-21T14:22:34.600Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:34	stdout	Logging in via password
2024/11/21 15:22:34	stdout	2024-11-21T14:22:34.325Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:34	stdout	Logging in via password
2024/11/21 15:22:34	stdout	2024-11-21T14:22:34.048Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:33	stdout	Logging in via password
2024/11/21 15:22:33	stdout	2024-11-21T14:22:33.770Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:33	stdout	Logging in via password
2024/11/21 15:22:33	stdout	2024-11-21T14:22:33.492Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:33	stdout	Logging in via password
2024/11/21 15:22:33	stdout	2024-11-21T14:22:33.184Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:32	stdout	Logging in via password
2024/11/21 15:22:32	stdout	2024-11-21T14:22:32.889Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:32	stdout	Logging in via password
2024/11/21 15:22:32	stdout	2024-11-21T14:22:32.606Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:32	stdout	Logging in via password
2024/11/21 15:22:32	stdout	2024-11-21T14:22:32.319Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:31	stdout	Logging in via password
2024/11/21 15:22:31	stdout	2024-11-21T14:22:31.863Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:31	stdout	Logging in via password
2024/11/21 15:22:31	stdout	2024-11-21T14:22:31.563Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:31	stdout	Logging in via password
2024/11/21 15:22:31	stdout	2024-11-21T14:22:31.243Z [32minfo[39m: GET 200 /account/validate
2024/11/21 15:22:31	stdout	2024-11-21T14:22:31.235Z [32minfo[39m: POST 200 /account/login
2024/11/21 15:22:30	stdout	Logging in via password`

3 minutes earlier a similar log can be seen etc. My guess is the server (and that might be a my-server-problem?) disconnects after being overwhelmed by the many login attempts, which seem to happen simultaneously to get data from each category and account separately rather than keeping the session alive to retrieve all data, then disconnect and connect (once) 3 minutes later again? Or am I complety wrong here? Any pointers are very much appreciated.

**Comment by jlvcm** [comment]
I've removed the historical data so it may help, but not sure


and btw, i'm using a "broken" version of actualpy to be compatible with home assistant, but it seems that one of the next HA releases will be compatible with the official version of actualpy so if you still have issues maybe wait a bit until HA update and i'll clean this up a bit

**Comment by Fywqdk** [comment]
Thanks for the update (also on Discord). It seems this fixed the issue :)
