### ISSUE TITLE
Add Currency to configuration

### ISSUE THREAD

**Issue by sam2332** [jlvcm/ha-actualbudget#2]
i am in the usa and the home assistant plugin is not respecting home assistants select currency 

https://github.com/jlvcm/ha-actualbudget/blame/569722c30c1fbc14bb3b202218370d69ca89626b/custom_components/actualbudget/const.py#L6

**Comment by jlvcm** [comment]
Now when adding an instance i've added a input so you can set up any currency you want, just update the plugin and re-add your instance and set the unit as '$' for example

it's not perfect but didn't had time to make it much better, but at-least you can use the addon with any currency

let me know if this work for you so i can close this issue, and thanks for the idea!

**Comment by s1mpleman** [comment]
> Now when adding an instance I've added an input so you can set up any currency you want, just update the plugin and re-add your instance and set the unit as '$' for example
> 
> it's not perfect but I didn't had time to make it much better, but at-least you can use the addon with any currency
> 
> let me know if this work for you so i can close this issue, and thanks for the idea!

Not OP but works perfectly fine for me.
