### ISSUE TITLE
Not a valid repository

### ISSUE THREAD

**Issue by ryceg** [jlvcm/ha-actualbudget#3]
Hey, just tried setting this up and it reckons that it's not a valid repository for HACS.

**Comment by jlvcm** [comment]
The project is still a bit young so its not in hacs yet but you should be able to add it manually

1.
<img width="933" alt="SCR-20240830-lpfj" src="https://github.com/user-attachments/assets/b8ebd9ca-ccc2-4f60-a9a9-6cf69b71cafe">

2.
<img width="492" alt="SCR-20240830-lovt" src="https://github.com/user-attachments/assets/1ed50bff-77a2-46d4-9dc1-3aff97ee585a">

3. restart home assistant, and add it in the Settings> Devices and services> Add integration> actualbudget

let me know if this works for you or if you still have a issue

**Comment by ryceg** [comment]
Oh god, egg on my face. Thanks!
