### ISSUE TITLE
Incorrect Decimal for Budget Items

### ISSUE THREAD

**Issue by daviswieck** [jlvcm/ha-actualbudget#5]
So for the accounts, all of the money matches up correctly in each account sensor. But for the budget itself the decimal is 2 decimal points off. For example, I have a budget line item for "Amazon". I have $50.00 budgeted, but the sensor shows $5,000.0. 

![image](https://github.com/user-attachments/assets/e7a436c2-b47c-4e83-93fe-a2870d4af80f)

**Comment by jlvcm** [comment]
Thanks for the report! It should be fixed now, you may need to go the integration in HACS and click "redownload" to update
<img width="854" alt="image" src="https://github.com/user-attachments/assets/5e8ef90f-8efa-48c6-a45b-6e40c60cff7d">


Let me know if this fixes it for you, and sorry about breaking your historical data 😅
