### ISSUE TITLE
Allow configuration of sensor prefix

### ISSUE THREAD

**Issue by stephanlinke87** [jlvcm/ha-actualbudget#9]
Happy to see a plugin like this emerge :) I set it up and what came to my attention is that the sensors use the category name as name, e.g. _sensor.groceries_. It would be better if we could add a prefix while configuring the integration, like _sensor.actualbudget_2024.groceries_ :) 

Thanks for your work on this, most appreciated :) I've been trying to get my budget into Home Assistant for a long time now :)

**Comment by jlvcm** [comment]
I agree!

i have changed that now.

you need to remove and re add the connection, so you can set whatever prefix you want, and to avoid breaking other users automations. I hope 🤞 

let me know if you get any issues with it, thanks for the feedback 🙏

**Comment by stephanlinke87** [comment]
Thats awesome, thanks! :) I‘ll check it out tomorrow, maybe I can track down the slow start up issue somehow… :)

**Comment by stephanlinke87** [comment]
Just tested the prefix, works as intended, thanks for the quick fix :)
